CREATE DATABASE IF NOT EXISTS FINDMYPAW_DB;

USE FINDMYPAW_DB;

DROP TABLE IF EXISTS ADOPCIONES;
DROP TABLE IF EXISTS NOTIFICACIONES;
DROP TABLE IF EXISTS IMAGENES_PERRO;
DROP TABLE IF EXISTS SOLICITUDES_ADOPCION;
DROP TABLE IF EXISTS REPORTES;
DROP TABLE IF EXISTS PERROS;
DROP TABLE IF EXISTS REFUGIOS;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TIPO_REPORTES;
DROP TABLE IF EXISTS ESTADOS;
DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES (
    ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ROL VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200)
);

CREATE TABLE ESTADOS (
    ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200)
);

CREATE TABLE TIPO_REPORTES (
    ID_TIPO_REPORTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TIPO_REPORTE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200)
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100),
    APELLIDO_MATERNO VARCHAR(100),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(200),
    FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE REFUGIOS (
    ID_REFUGIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    NOMBRE_REFUGIO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(200),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE PERROS (
    ID_PERRO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_REFUGIO INT,
    ID_ESTADO INT NOT NULL,
    NOMBRE_PERRO VARCHAR(100),
    RAZA VARCHAR(100),
    EDAD INT,
    TAMANO VARCHAR(50),
    COLOR VARCHAR(50),
    SEXO VARCHAR(20),
    DESCRIPCION TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_REFUGIO) REFERENCES REFUGIOS(ID_REFUGIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE REPORTES (
    ID_REPORTE INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_PERRO INT NOT NULL,
    ID_TIPO_REPORTE INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    UBICACION VARCHAR(200) NOT NULL,
    FECHA_REPORTE DATE NOT NULL,
    DESCRIPCION TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PERRO) REFERENCES PERROS(ID_PERRO),
    FOREIGN KEY (ID_TIPO_REPORTE) REFERENCES TIPO_REPORTES(ID_TIPO_REPORTE),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE SOLICITUDES_ADOPCION (
    ID_SOLICITUD INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_PERRO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    COMENTARIO TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PERRO) REFERENCES PERROS(ID_PERRO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE IMAGENES_PERRO (
    ID_IMAGEN INT AUTO_INCREMENT PRIMARY KEY,
    ID_PERRO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    RUTA_IMAGEN VARCHAR(200) NOT NULL,
    DESCRIPCION VARCHAR(200),
    FOREIGN KEY (ID_PERRO) REFERENCES PERROS(ID_PERRO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_REPORTE INT,
    ID_SOLICITUD INT,
    ID_ESTADO INT NOT NULL,
    MENSAJE TEXT NOT NULL,
    FECHA_NOTIFICACION DATE NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_REPORTE) REFERENCES REPORTES(ID_REPORTE),
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES_ADOPCION(ID_SOLICITUD),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

CREATE TABLE ADOPCIONES (
    ID_ADOPCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_SOLICITUD INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_PERRO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    FECHA_ADOPCION DATE NOT NULL,
    OBSERVACION TEXT,
    FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES_ADOPCION(ID_SOLICITUD),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PERRO) REFERENCES PERROS(ID_PERRO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)
);

INSERT INTO ROLES (NOMBRE_ROL, DESCRIPCION) VALUES
('Usuario General', 'Persona que puede reportar perros perdidos o abandonados'),
('Rescatista', 'Persona o refugio que ayuda en el rescate y adopción'),
('Administrador', 'Usuario encargado de administrar la aplicación');

INSERT INTO ESTADOS (NOMBRE_ESTADO, DESCRIPCION) VALUES
('Activo', 'Registro disponible dentro del sistema'),
('Inactivo', 'Registro deshabilitado dentro del sistema'),
('Pendiente', 'Registro en espera de revisión'),
('Aprobado', 'Registro aprobado'),
('Rechazado', 'Registro rechazado'),
('Adoptado', 'Perro que ya fue adoptado'),
('Perdido', 'Perro reportado como perdido'),
('Encontrado', 'Perro reportado como encontrado'),
('En adopción', 'Perro disponible para adopción');

INSERT INTO TIPO_REPORTES (NOMBRE_TIPO_REPORTE, DESCRIPCION) VALUES
('Perro perdido', 'Reporte de un perro extraviado'),
('Perro encontrado', 'Reporte de un perro encontrado en la calle'),
('Perro abandonado', 'Reporte de un perro en condición de abandono');

INSERT INTO USUARIOS (
    ID_ROL,
    ID_ESTADO,
    CORREO,
    CONTRASENA,
    NOMBRE_USUARIO,
    APELLIDO_PATERNO,
    APELLIDO_MATERNO,
    TELEFONO,
    DIRECCION
) VALUES
(1, 1, 'usuario@gmail.com', '12345', 'Carlos', 'Mora', 'Soto', '8888-8888', 'Heredia'),
(2, 1, 'rescatista@gmail.com', '12345', 'María', 'Gómez', 'Rojas', '7777-7777', 'San José'),
(3, 1, 'admin@gmail.com', '12345', 'Administrador', 'Sistema', 'FindMyPaw', '6666-6666', 'Costa Rica');

INSERT INTO REFUGIOS (
    ID_USUARIO,
    ID_ESTADO,
    NOMBRE_REFUGIO,
    CORREO,
    TELEFONO,
    DIRECCION
) VALUES
(2, 1, 'Refugio Patitas Felices', 'patitas@gmail.com', '2222-2222', 'San José, Costa Rica');

INSERT INTO PERROS (
    ID_USUARIO,
    ID_REFUGIO,
    ID_ESTADO,
    NOMBRE_PERRO,
    RAZA,
    EDAD,
    TAMANO,
    COLOR,
    SEXO,
    DESCRIPCION
) VALUES
(1, NULL, 7, 'Max', 'Labrador', 3, 'Grande', 'Dorado', 'Macho', 'Perro perdido cerca del parque central'),
(2, 1, 9, 'Luna', 'Mestiza', 2, 'Mediano', 'Blanco', 'Hembra', 'Perrita rescatada disponible para adopción');

INSERT INTO REPORTES (
    ID_USUARIO,
    ID_PERRO,
    ID_TIPO_REPORTE,
    ID_ESTADO,
    UBICACION,
    FECHA_REPORTE,
    DESCRIPCION
) VALUES
(1, 1, 1, 1, 'Heredia Centro', '2026-07-03', 'Max fue visto por última vez cerca del parque central');

INSERT INTO SOLICITUDES_ADOPCION (
    ID_USUARIO,
    ID_PERRO,
    ID_ESTADO,
    FECHA_SOLICITUD,
    COMENTARIO
) VALUES
(1, 2, 3, '2026-07-03', 'Estoy interesado en adoptar a Luna');

INSERT INTO IMAGENES_PERRO (
    ID_PERRO,
    ID_ESTADO,
    RUTA_IMAGEN,
    DESCRIPCION
) VALUES
(1, 1, 'img/max.jpg', 'Fotografía de Max'),
(2, 1, 'img/luna.jpg', 'Fotografía de Luna');

INSERT INTO NOTIFICACIONES (
    ID_USUARIO,
    ID_REPORTE,
    ID_SOLICITUD,
    ID_ESTADO,
    MENSAJE,
    FECHA_NOTIFICACION
) VALUES
(1, 1, NULL, 1, 'Su reporte fue registrado correctamente', '2026-07-03'),
(1, NULL, 1, 3, 'Su solicitud de adopción está pendiente de revisión', '2026-07-03');

INSERT INTO ADOPCIONES (
    ID_SOLICITUD,
    ID_USUARIO,
    ID_PERRO,
    ID_ESTADO,
    FECHA_ADOPCION,
    OBSERVACION
) VALUES
(1, 1, 2, 3, '2026-07-03', 'Adopción pendiente de aprobación final');